[package]
name = "zxcvbn-rs-py"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "zxcvbn_rs_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.3"
zxcvbn = "2.2.2"
